# https://taskfile.dev

version: '3'

vars:
  ORGANISATION: jsdrews
  PROJECT: mongo-migrations
  VERSION: 1.0.0
  TAG: latest

tasks:
  default:
    cmds:
      - task -a
    silent: true

  build:
    cmds:
      - docker build -t {{ .ORGANISATION }}/{{ .PROJECT }}:{{ .VERSION }} .
      - docker tag {{ .ORGANISATION }}/{{ .PROJECT }}:{{ .VERSION }} {{ .ORGANISATION }}/{{ .PROJECT }}:{{ .TAG }}
    silent: true

  rmi:
    cmds:
      - docker rmi {{ .ORGANISATION }}/{{ .PROJECT }}:{{ .VERSION }}
      - docker rmi {{ .ORGANISATION }}/{{ .PROJECT }}:{{ .TAG }}
    silent: true

  publish:
    cmds:
      - docker push {{ .ORGANISATION }}/{{ .PROJECT }}:{{ .VERSION }}
      - docker push {{ .ORGANISATION }}/{{ .PROJECT }}:{{ .TAG }}
    silent: true
